import time




def intro():
    time.sleep(3)
    print("*Ring ring*")
    time.sleep(1)
    print("*Ring ring*")
    time.sleep(1)
    print("Hello? Hello, hello?")
    time.sleep(0.5)
    print("Mark: Hello?")
    time.sleep(1)
    print("Uhhh..")
    time.sleep(1)
    print("I wanted to record this message for you, to help you get settle in on your first night.")
    time.sleep(3)
    print("Uh, The animatronic characters here, do get a bit quirky at night...")
    time.sleep(1)
    print("Mark: Quirky? What does that mean?")
    time.sleep(3)
    print("But don't worry, your office contains lights to scare them away if they get too close.")
    time.sleep(4)
    print("We've also equiped you with a monitor to view the pizzeria's cameras.")
    time.sleep(3)
    print("Although this all sounds great, I do advise you not to use too many devices at once.")
    time.sleep(4)
    print("Be sure to close the doors only if absolutely necessary.")
    time.sleep(5)
    print("But other than that, you'll be fine!")
    time.sleep(3)
    print("Alright, I'll leave you to it, your shift ends at 6AM.")
    time.sleep(2)
    print("Good luck and good night!")
    time.sleep(1)
    print("Mark: Thank you Mr.Phone guy!")
    time.sleep(1.5)
    print("*Click*")
    time.sleep(2)
    print("It is 12AM")